version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: mysql_sqs
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqs
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: