server:
  port: 8080
spring:
  application:
    name: sqs
  datasource:
    url: jdbc:mysql://localhost:3306/sqs?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect